#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka/
#server:
#  port: 8085
spring:
  application:
    name: charMe
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.86.201:3306/wx?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: ENC(vj6RHAkuT7UvXf5GiKKVdA==)
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #数据库索引
    database: 0 
    host: ENC(FVFRGTDT5QVSJbEfoGADCNCyZHNiTyOp)
    port: 8080
    password: 
    timeout: 5000
    lettuce:
      pool:
        #最大连接数(负数代表没有限制)
        max-active: 9
        #最大阻塞等待时间(负数代表没有限制)
        max-wait: -1
        #最大空闲连接数
        max-idle: 5
        #最小空闲连接数
        min-idle: 0
  
mybatis:
  mapper-locations: classpath*:com/yzeng/mapper/**/*Mapper.xml
  type-aliases-package: com.yzeng.entity    
jasypt:
  encryptor:
    password: yzblog  
    
#是否激活 swagger true or false
swagger:
  is:
    enable: true   
          
    
  