spring:
  redis:
    #数据库索引
    database: 0 
    host: 139.199.86.201
    port: 8080
    password: 
    timeout: 5000
    lettuce:
      pool:
        #最大连接数(负数代表没有限制)
        max-active: 9
        #最大阻塞等待时间(负数代表没有限制)
        max-wait: -1
        #最大空闲连接数
        max-idle: 5
        #最小空闲连接数
        min-idle: 0
      
          
    
      